services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: backend/variables.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
#      - mongodb
      - redis

#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: backend/variables.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  mongodb:
#    image: mongo:7
#    container_name: mongodb
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodata:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
#  mongodata:
