services:
#  backend:
#    build:
#      context: ./backend
#    container_name: backend
#    env_file: backend/variables.env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
##      - mongodb
#      - redis

#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: backend/variables.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  mongodb:
#    image: mongo:7
#    container_name: mongodb
#    restart: always
#    env_file: backend/variables.env
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodata:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  pgdata:
#  mongodata:
  redisdata:
